### ISSUE TITLE
[typo] kata "dijelakan" dengan maksud "dijelaskan"

### ISSUE THREAD

**Issue by thexdev** [gungunfebrianza/Belajar-Dengan-Jenius-AWS-Node.js#1]
Assalamualaikum. Saya menemukan sebuah typo pada penulisan kata "dijelakan" yang mungkin memiliki maksud "dijelaskan" pada **Chapter 1** - **Subchapter 1** - **Objective** _**Ecmascript**_. Terletak pada paragraf pertama, baris pertama, urutan kata keenam dari sebelah kiri.

**Tambahan**
Pada paragraf pertama, baris ketiga, urutan kata kelima dari sebelah kiri, yaitu "didalam" seharusnya dituliskan secara terpisah sehingga menjadi "di dalam".

**Referensi**
- [Wikipedia - Preposisi](https://id.wikipedia.org/wiki/Preposisi)

**Comment by gungunfebrianza** [comment]
waw amazing, makasih bantu koreksi, tolong di info terus ya, biar akang bisa saya catat dibuku sebagai kontributor ^_^

**Comment by thexdev** [comment]
Terimakasih. Akan saya teruskan demi memberikan ilmu yang bermanfaat bagi
orang banyak :).

Pada tanggal Jum, 24 Apr 2020 20.50, Gun Gun Febrianza <
notifications@github.com> menulis:
