### ISSUE TITLE
Pada Content Delivery Network (CDN) itu maksudnya sebuah atau sekumpulan ?

### ISSUE THREAD

**Issue by ArmaOne** [gungunfebrianza/Belajar-Dengan-Jenius-AWS-Node.js#2]
Content Delivery Network (CDN) atau Content Distribution Network (CDN) **sebuah** 
**sekumpulan** server yang secara geografis saling terhubung di berbagai negara untuk 
menyediakan layanan penyajian konten internet yang sangat cepat.

**Comment by gungunfebrianza** [comment]
makasih koreknya ya @ArmaOne harusnya sekumpulan server :)

**Comment by gungunfebrianza** [comment]
di versi selanjutnya saya perbaiki ya
